language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - phpenv config-rm xdebug.ini
  - ./.travis.scripts/compile.sh

notifications:
  email:
    derick@xdebug.org

script:
  - MYPHP=`make findphp`
  - export PATH=`dirname $MYPHP`:$PATH
  - $MYPHP -c /tmp/temp-php-config.ini -v
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$MYPHP $MYPHP -c /tmp/temp-php-config.ini -dxdebug.auto_trace=0 run-tests.php -q -x --show-diff

notifications:
  irc: "irc.freenode.org#xdebug"
